apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-namespace-config
spec:
  rules:
  - name: generate-configmap-for-namespace
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: ConfigMap
      name: ns-default-config
      namespace: "{{request.object.metadata.name}}"
      data:
        welcome: "This namespace is managed by Kyverno"
        created-by: "policy/generate-namespace-config"
